'\" t
.\"     Title: pam_whawty
.\"    Author: [see the "AUTHORS" section]
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 05/15/2016
.\"    Manual: \ \&
.\"    Source: \ \&
.\"  Language: English
.\"
.TH "PAM_WHAWTY" "8" "05/15/2016" "\ \&" "\ \&"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
pam_whawty \- PAM module for whawty\&.auth
.SH "SYNOPSIS"
.sp
.nf
pam_whawty\&.so
  [ \fBdebug\fR ]
  [ \fBtry_first_pass\fR ]
  [ \fBuse_first_pass\fR ]
  [ \fBnot_set_pass\fR ]
  [ \fBsock=</path/to/whawty/socket>\fR ]
  [ \fBtimeout=<seconds>\fR ]
.fi
.SH "DESCRIPTION"
.sp
\fBpam_whawty\fR is a pam module which uses \fIwhawty\&.auth\fR as authentication backend\&. In order for \fBpam_whawty\fR to work the \fIwhawty\&.auth\fR app must be running on the machine\&. Since \fIwhawty\&.auth\fR uses the same protocol as \fIsaslauthd\fR \fBpam_whawty\fR might as well be used to authenticate against \fIsaslauthd\fR\&.
.SH "OPTIONS"
.sp
The following options can be passed to the \fBpam_whawty\fR module\&.
.PP
\fBdebug\fR
.RS 4
This turns on additional logging using
\fBsyslog\fR(3)\&.
.RE
.PP
\fBtry_first_pass\fR
.RS 4
This instructs
\fBpam_whawty\fR
to try the password of a previous module from the stack\&. Only if there is no password found it will ask the user for a password\&.
.RE
.PP
\fBuse_first_pass\fR
.RS 4
This is similar to
\fBtry_first_pass\fR
but if no password is found on the stack the module fails\&.
\fBpam_whawty\fR
will not try to get the password from the user\&.
.RE
.PP
\fBnot_set_pass\fR
.RS 4
By default
\fBpam_whawty\fR
pushes a fetched password onto the stack for other modules to be used\&. If this option is set the password is not pushed onto the stack\&.
.RE
.PP
\fBsock=\fR\fI</path/to/whawty/socket>\fR
.RS 4
This option can be used to configure the path to the whawty\&.auth unix socket\&. By default
\fI/var/run/whawty/auth\&.sock\fR
is used\&.
.RE
.PP
\fBtimeout=\fR\fI<seconds>\fR
.RS 4
In case the authentication daemon does not respond to authentication requests by default
\fBpam_whawty\fR
will report an authentication failure after 3 seconds\&. This option makes this period configurable\&.
.RE
.SH "MODULE TYPES PROVIDED"
.sp
Only module type \fBauth\fR is provided however it is not possible to change passwords using this module\&.
.SH "BUGS"
.sp
Most likely there are some bugs in \fBpam_whawty\fR\&. If you find a bug, please let the developers know at http://github\&.com/whawty/auth\&. Of course, pull requests are preferred\&.
.SH "SEE ALSO"
.sp
\fBpam\&.conf\fR(5), \fBpamd\&.d\fR(5), \fBpam\fR(7), \fBwhawty\-auth\fR(8)
.SH "AUTHORS"
.sp
Christian Pointner <equinox@spreadspace\&.org>
.SH "RESOURCES"
.sp
Main web site: http://github\&.com/whawty/auth
